### ISSUE TITLE
Meteor 3.0 Support

### ISSUE THREAD

**Issue by dallman2** [Meteor-Community-Packages/meteor-user-status#181] opened 2024-02-07 19:57 UTC
Will this package be updated to be compatible with Meteor 3.0? Currently, it fails to build on Meteor 3.0 without modifications to both the `client.js` and `server.js`.

Thanks

**Comment by StorytellerCZ** [comment] 2024-02-21 07:29
Closing as this is duplicate of #173

**Closed by StorytellerCZ** 2024-02-21 07:29 UTC
